/* =====================================================================
   LCG · Seguimiento Comercial — Base de cuentas
   ---------------------------------------------------------------------
   Generado a partir de "Seguimiento_Comercial_KRAM.xlsx" (42 cuentas)
   más las altas posteriores hechas a mano.
   Los valores son idénticos a los del Excel original: los campos que en
   el archivo venían como "-" se conservan así y la interfaz los muestra
   como "—". No agregues datos inventados.

   Para dar de alta una cuenta nueva, copia una línea y edítala.
   El campo "id" debe ser único (minúsculas, sin acentos, con guiones);
   es la llave con la que se guarda el seguimiento en el navegador.
   ===================================================================== */

const CUENTAS_INICIALES = [
  {"id": "oleofinos", "empresa": "Oleofinos", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Carlos Visbal", "cargo": "Director de Estrategia y Finanzas", "telefono": "55 2948 6213", "correo": "carlos.visbal@oleofinos.com.mx"},
  {"id": "frutas-finas-de-tancitaro", "empresa": "Frutas Finas de Tancítaro", "clasificacion": "AAA", "estado": "Michoacán", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Diana Laura Flores", "cargo": "CFO", "telefono": "45 2545 5348", "correo": "d.flores@fftancitaro.com"},
  {"id": "agromich", "empresa": "Agromich", "clasificacion": "A", "estado": "Michoacán", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Juan Martín Rivera", "cargo": "CEO", "telefono": "45 2525 6008", "correo": "direccion@agromich.com"},
  {"id": "alianza-team", "empresa": "Alianza Team", "clasificacion": "AAA", "estado": "Michoacán", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Luis Carlos McNish", "cargo": "Director de Operaciones", "telefono": "44 3222 1132", "correo": "lmcnish@alianzateam.com"},
  {"id": "grupo-tron", "empresa": "Grupo TRON", "clasificacion": "AA", "estado": "Michoacán", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Gregorio Gómez González", "cargo": "CEO", "telefono": "44 3128 1799", "correo": "gregorio.gomez@saporis.mx"},
  {"id": "el-gran-chaparral", "empresa": "El Gran Chaparral", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Javier Casillas", "cargo": "Director General Adjunto", "telefono": "37 8885 3764", "correo": "jcasillas@chaparral.com.mx"},
  {"id": "imag-organics", "empresa": "IMAG Organics", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Gilberto Barranco Trejo", "cargo": "Director Comercial", "telefono": "37 8186 9479", "correo": "gbarranco@imagorganics.com"},
  {"id": "la-chicharronera", "empresa": "La Chicharronera", "clasificacion": "A", "estado": "Jalisco", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Óscar Martin", "cargo": "CEO", "telefono": "37 8116 6000", "correo": "oscartepa@hotmail.com"},
  {"id": "grupo-delta", "empresa": "Grupo Delta", "clasificacion": "A", "estado": "Michoacán", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Efraín Bribiesca", "cargo": "Gerente Comercial", "telefono": "35 2125 3363", "correo": "efrainbr@grupodelta.com.mx"},
  {"id": "turbomaquinas", "empresa": "Turbomáquinas", "clasificacion": "AA", "estado": "Michoacán", "zona": "Occidente", "industria": "Maquinaria", "contacto": "Carlos García Arelle", "cargo": "CEO", "telefono": "35 2100 4044", "correo": "carlos.garcia@turbomaquinas.com"},
  {"id": "ducor", "empresa": "DUCOR", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Marco Cornejo", "cargo": "Director Comercial", "telefono": "33 3559 6595", "correo": "cornejo.marco@ducor.com.mx"},
  {"id": "grupo-urrea", "empresa": "Grupo URREA", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Retail", "contacto": "Alfonso Urrea", "cargo": "CEO", "telefono": "33 3440 5469", "correo": "aurrea@urrea.net"},
  {"id": "grupo-avicola-quinones", "empresa": "Grupo Avícola Quiñones", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Francisco Quiñones Sánchez", "cargo": "CEO", "telefono": "33 3156 0527", "correo": "fquinones@gaq.com.mx"},
  {"id": "esgari", "empresa": "Esgari", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Operador Logístico", "contacto": "Ernesto Donnadieu", "cargo": "CEO", "telefono": "33 3147 0625", "correo": "edonnadieuc@esgari.com.mx"},
  {"id": "productos-de-trigo", "empresa": "Productos de Trigo", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Juan Ignacio Pérez", "cargo": "Director General", "telefono": "33 1606 9483", "correo": "iperez@prodetrigo.com"},
  {"id": "grupo-vida", "empresa": "Grupo Vida", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Luis Jorge Gómez", "cargo": "Director Agroindustrial", "telefono": "33 1603 5118", "correo": "luisjo.gomez@fgfholding.com"},
  {"id": "grupo-premier-de-occidente", "empresa": "Grupo Premier de Occidente", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Diego Valencia Iriarte", "cargo": "Director Comercial", "telefono": "33 1278 5216", "correo": "dvi@gpopremier.com"},
  {"id": "tajin", "empresa": "Tajín", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Alejandra Gómez Maravel", "cargo": "Directora de Innovación y Productividad", "telefono": "33 1133 5036", "correo": "alejandra.gomez@tajin.com"},
  {"id": "natura-biofoods", "empresa": "Natura BioFoods", "clasificacion": "A", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Enrique Gómez", "cargo": "Director de Planeación Estratégica", "telefono": "33 1066 0441", "correo": "enrique.gomez@nbf.mx"},
  {"id": "limones-monica", "empresa": "Limones Mónica", "clasificacion": "A", "estado": "Jalisco", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Sergio Cortés Domínguez", "cargo": "Dueño", "telefono": "23 2124 8756", "correo": "sergioc@limonik.mx"},
  {"id": "toyo-foods", "empresa": "Toyo Foods", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Retail", "contacto": "-", "cargo": "-", "telefono": "-", "correo": "-"},
  {"id": "price-shoes", "empresa": "Price Shoes", "clasificacion": "AAA", "estado": "Ciudad de México", "zona": "Metro", "industria": "Bienes de Consumo", "contacto": "-", "cargo": "-", "telefono": "-", "correo": "-"},
  {"id": "productos-de-consumo-z", "empresa": "Productos de Consumo Z", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Retail", "contacto": "Celia Martínez Fernández", "cargo": "Directora Retail", "telefono": "-", "correo": "cmartinez@pcz.com.mx"},
  {"id": "grupo-merza", "empresa": "Grupo MERZA", "clasificacion": "AAA", "estado": "Michoacán", "zona": "Occidente", "industria": "Retail", "contacto": "Guillermo Valdés Vega", "cargo": "Presidente", "telefono": "-", "correo": "gvega@merza.com"},
  {"id": "super-kiosko", "empresa": "Super Kiosko", "clasificacion": "AAA", "estado": "Colima", "zona": "Occidente", "industria": "Retail", "contacto": "Fernando Velasco Márquez", "cargo": "CEO", "telefono": "-", "correo": "fvelasco@mikiosko.mx"},
  {"id": "grupo-chocolate-ibarra", "empresa": "Grupo Chocolate Ibarra", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Ernesto Gómez Ibarra", "cargo": "Presidente", "telefono": "-", "correo": "egi@grupochocolateibarra.com"},
  {"id": "verde-valle", "empresa": "Verde Valle", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Germán Rosales Wybo", "cargo": "Co-Director General", "telefono": "-", "correo": "germanrw@verdevalle.com"},
  {"id": "corporativo-fragua", "empresa": "Corporativo FRAGUA", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Retail", "contacto": "Javier Arroyo Navarro", "cargo": "CEO", "telefono": "-", "correo": "presidencia@camaradecomerciogdl.mx"},
  {"id": "ferrero", "empresa": "Ferrero", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Pietro Cornero", "cargo": "Presidente", "telefono": "-", "correo": "pietro.cornero@ferrero.com"},
  {"id": "dulces-de-la-rosa", "empresa": "Dulces de la Rosa", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Jacobo Michel", "cargo": "Subdirector General", "telefono": "-", "correo": "-"},
  {"id": "grupo-tecnaal", "empresa": "Grupo Tecnaal", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Liliana Piñeyro", "cargo": "CFO", "telefono": "-", "correo": "dirfinanzas@grupotecnaal.com.mx"},
  {"id": "sesajal", "empresa": "Sesajal", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Iñigo González", "cargo": "CEO", "telefono": "-", "correo": "inigo@sesajal.com"},
  {"id": "grupo-islo", "empresa": "Grupo Islo", "clasificacion": "AAA", "estado": "Zacatecas", "zona": "Bajío", "industria": "Agronegocio", "contacto": "Eduardo López Muñoz", "cargo": "Presidente", "telefono": "-", "correo": "eduardo.lopez@grupoislo.com"},
  {"id": "grupo-industrial-michel", "empresa": "Grupo Industrial Michel", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Antonio Michel", "cargo": "Director General", "telefono": "-", "correo": "-"},
  {"id": "calkins-burke-and-zannie-de-mexico", "empresa": "Calkins Burke and Zannie de México", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Marco Antonio Zannie", "cargo": "CEO", "telefono": "-", "correo": "marcozannie@mexcorina.com"},
  {"id": "sanchez-y-martin", "empresa": "Sánchez y Martín", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Fernando Sánchez Vera", "cargo": "CEO", "telefono": "-", "correo": "fsanchez@sym.com.mx"},
  {"id": "simplot-mexico", "empresa": "Simplot México", "clasificacion": "AAA", "estado": "Michoacán", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Luis Alberto Rodríguez Mastache", "cargo": "CEO", "telefono": "-", "correo": "luis.rodriguez@simplot.com"},
  {"id": "site-plasticos", "empresa": "SITE Plásticos", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Manufactura", "contacto": "Luis Rodrigo Villaseñor Franco", "cargo": "CEO", "telefono": "-", "correo": "rvillasenor@gpoirm.com"},
  {"id": "sunopta", "empresa": "SUNOPTA", "clasificacion": "AAA", "estado": "Michoacán", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Brian Kocher", "cargo": "CEO", "telefono": "-", "correo": "brian.kocher@sunopta.com"},
  {"id": "trenzados-marinos-grupo-ortiz", "empresa": "Trenzados Marinos (Grupo Ortiz)", "clasificacion": "AAA", "estado": "Michoacán", "zona": "Occidente", "industria": "Manufactura", "contacto": "Javier de la Mata Medina", "cargo": "CEO", "telefono": "-", "correo": "fjavier.delamata@grupoortiz.com"},
  {"id": "vivri", "empresa": "VIVRI", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Luis de la Torre Rábago", "cargo": "Presidente", "telefono": "-", "correo": "luis@vivri.com"},
  {"id": "wendy-colchones", "empresa": "Wendy Colchones", "clasificacion": "AAA", "estado": "Jalisco", "zona": "Occidente", "industria": "Bienes de Consumo", "contacto": "Manuel López Castillejos", "cargo": "CEO", "telefono": "-", "correo": "mlc@wendy.com.mx"},
  {"id": "alipec", "empresa": "Alipec", "clasificacion": "AA", "estado": "Jalisco", "zona": "Occidente", "industria": "Agronegocio", "contacto": "Juan Lorenzo Delgado", "cargo": "Subdirector de Operaciones", "telefono": "-", "correo": "jdelgado@alipec.com"}
];
